name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
        
    - name: Install NPM packages
      working-directory: ./SDSetupFrontend
      run: npm ci
      
    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
        
    - name: Build Frontend
      working-directory: ./SDSetupFrontend
      run: npm run build
        
    - name: Build Common
      run: dotnet build -c Release SDSetupCommon
      
    - name: Build Backend
      run: dotnet build -c Release -r linux-x64 SDSetupBackend
      
    - name: Build Manager
      run: dotnet build -c Release SDSetupManager
